spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: user
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/tasks
springdoc:
  swagger-ui:
    path: /api-docs.html
